package client

// Info represents a client's information.
type Info struct {

	// ID is the unique identifier for the client.
	ID string

	// ConnectionId generated by client, used to identify the client connection.
	ConnectionId string

	// Version is the version of the client.
	Version string

	// AliveAt is the time the client was last seen.
	AliveAt int64

	// ConnectionAt is the time the client was connected.
	ConnectionAt int64

	// Gateway is the name of the gateway the client is connected to.
	Gateway string

	// CliAddr is the address of the client.
	CliAddr string
}
